site_name: Contact Anonymiser
site_description: Enables you to anonymise contacts without losing the statistical information
site_author: SYSTOPIA
repo_url: https://github.com/systopia/de.systopia.anonymiser

theme:
  name: material

nav:
  - Introduction: index.md

markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.mark

plugins:
  - search:
      lang: en
